name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Blix Plugins
        run: cd ./blix-plugins/glfx-plugin && npm ci && npm run build

      - name: Build/Release Blix
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            npm run dist -- --linux deb
          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
            npm run dist -- --windows nsis
          elif [ "${{ matrix.os }}" = "macos-latest' ]; then
            echo "macOS build not supported yet"
          fi
        env:
          GH_TOKEN: ${{ secrets.TEST_TOKEN }}